### ISSUE TITLE
Implement client secret creation for universal auth

### ISSUE THREAD

**Issue by vtmocanu** [Infisical/provider-infisical#4]
Currently you can create an Identity, but I saw no way to also create a Client Secret for it.
I see that the terraform provider offers this functionality.
Thank you for creating this crossplane provider!

**Comment by vtmocanu** [comment]
Also tried like this:
```
apiVersion: identity.crossplane.infisical.com/v1alpha1
kind: Identity
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/identity
  labels:
    testing.upbound.io/example-name: universal-auth
  name: universal-auth-test
spec:
  forProvider:
    name: universal-auth-test
    orgId: MYORGID
    role: member
```

and 
```
apiVersion: identity.crossplane.infisical.com/v1alpha1
kind: UniversalAuth
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/universalauth
  labels:
    testing.upbound.io/example-name: universal-auth
  name: universal-auth-test
spec:
  forProvider:
    identityId: MYID
    # identityIdRef:
    #   name: universal-auth-test
    accessTokenTtl: 2592000 # 30 days in seconds
    accessTokenMaxTtl: 5184000 # 60 days in seconds
    accessTokenNumUsesLimit: 0 # 0 means unlimited uses
```

but it gives me:
```
  Warning  CannotObserveExternalResource  27s                  managed/identity.crossplane.infisical.com/v1alpha1, kind=universalauth  cannot run refresh: refresh failed: Error reading identity universal auth: Couldn't read identity universal auth from Infiscial, unexpected error: GetIdentityUniversalAuth: Unsuccessful response. [response={"reqId":"req-pyz3Hk6L1KtsUY","statusCode":400,"message":"The identity does not have universal auth","error":"BadRequest"}]
```
